-- Schema de Banco de Dados para Supabase
-- Habilita extensão geoespacial (opcional, caso queira queries geográficas complexas depois)
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;

-- Tabela mestre de veículos
CREATE TABLE public.vehicles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vehicle_id TEXT UNIQUE NOT NULL,     -- ex: 'truck-01'
    name TEXT NOT NULL,                  -- ex: 'Caminhão 01'
    type TEXT DEFAULT 'truck',           -- 'truck', 'motorcycle', 'car'
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de histórico de posições (telemetria)
CREATE TABLE public.vehicle_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id TEXT NOT NULL REFERENCES public.vehicles(vehicle_id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    speed REAL,                          -- velocidade em km/h
    heading REAL,                        -- direção em graus (0-360)
    battery_level REAL,                  -- nível de bateria em porcentagem (0-100)
    status TEXT,                         -- 'moving', 'idle', 'stopped', 'offline'
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabela de alertas recebidos
CREATE TABLE public.vehicle_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id TEXT NOT NULL REFERENCES public.vehicles(vehicle_id) ON DELETE CASCADE,
    alert_type TEXT NOT NULL,            -- ex: 'low_battery', 'sos'
    severity TEXT DEFAULT 'info',        -- 'info', 'warning', 'critical'
    message TEXT,
    latitude DOUBLE PRECISION,           -- Opcional: local onde ocorreu o alerta
    longitude DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Índices para otimização de queries de histórico e dashboards
CREATE INDEX idx_positions_vehicle_time ON public.vehicle_positions(vehicle_id, recorded_at DESC);
CREATE INDEX idx_positions_time ON public.vehicle_positions(recorded_at DESC);
CREATE INDEX idx_alerts_vehicle_time ON public.vehicle_alerts(vehicle_id, created_at DESC);

-- Opcional: View para pegar sempre a última posição conhecida de cada veículo
CREATE OR REPLACE VIEW public.latest_vehicle_positions AS
SELECT DISTINCT ON (vehicle_id)
    vehicle_id,
    latitude,
    longitude,
    speed,
    heading,
    battery_level,
    status,
    recorded_at
FROM public.vehicle_positions
ORDER BY vehicle_id, recorded_at DESC;

-- Regras básicas de RLS (Row Level Security) - Permite leitura e escrita anônima
-- AVISO: Apenas para fins acadêmicos. Em produção, exija autenticação.
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous select on vehicles" ON public.vehicles FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert on vehicles" ON public.vehicles FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous select on vehicle_positions" ON public.vehicle_positions FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert on vehicle_positions" ON public.vehicle_positions FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous select on vehicle_alerts" ON public.vehicle_alerts FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert on vehicle_alerts" ON public.vehicle_alerts FOR INSERT WITH CHECK (true);
